namespace ApiStudioIO
{
    using System;
    using System.ComponentModel;

    public abstract class ApiStudioComponentHeaderBase : IApiStudioComponent
    {
        [Category("Definition")]
        public string Name { get; set; }

        [Category("Definition")]
        public string Description { get; set; }

        [Category("Configuration")]
        public bool IsRequired { get; set; }

        [Category("Configuration")]
        public bool AllowEmptyValue { get; set; }

        [Category("ApiStudio Metadata")]
        public bool IsAutoGenerated { get; internal set; }
    }
}
