namespace ApiStudioIO
{
    using System;
    using System.ComponentModel;

    public class ApiStudioComponentHeaderResponse : ApiStudioComponentHeaderBase
    {
        // public static implicit operator ApiStudioComponentHeaderResponse(HttpApiHeaderResponse domain)
        // {
        //     var apiStudioComponent = new ApiStudioComponentHeaderResponse
        //     {
        //         Name = domain.Name,
        //         Description = domain.Description,
        //         IsRequired = domain.IsRequired,
        //         AllowEmptyValue = domain.AllowEmptyValue,
        //         IsAutoGenerated = domain.IsAutoGenerated,
        //         IncludeOn = domain.IncludeOn
        //     };
        //     return apiStudioComponent;
        // }

        [Category("Scope")]
        public HttpApiHeaderResponseOnTypes IncludeOn { get; set; }

        [Category("Hidden")]
        [Browsable(false)]
        public string IncludeOnName => $"{Enum.GetName(typeof(HttpApiHeaderResponseOnTypes), IncludeOn)}";
    }
}