//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiStudioIO
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ApiStudio";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Azure Function (ApiStudio)";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ApiStudioIODiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ApiStudioIOCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ApiStudioIOExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ApiStudioIOCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewApiStudioIOExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ApiStudioIOCommandSetId), 0x0001);
	
		// Package identifier
		public const string ApiStudioIOPackageId = "4a6ef9c8-3428-4bd6-9b17-c57b4285bbd8";
		
		// Editor factory identifier
		public const string ApiStudioIOEditorFactoryId = "7adec530-a54b-4af5-8284-6edc08e65131";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ApiStudioIOModelExplorerToolWindowId = "77787602-b5e7-42c4-970f-bdadafcb1c22";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace ApiStudioIO
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ApiStudioIOCommandSetId = "e1d0838c-7419-47d8-b56c-3d0aaaedbdb5";
	}
}