//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace ApiStudioIO
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(ApiStudioIOExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(ApiStudioIOExplorerToolWindow), Constants.ApiStudioIOEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@ApiStudio - ResourcesToolboxTab;api-studio.designer.dll", "ApiStudioIO.ApiStudio - ResourcesToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - ResourcesToolboxTab",
					"@ResourceAssociationToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.ResourceAssociationToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordResourceToResource", 
					"@ResourceAssociationToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - ResourcesToolboxTab",
					"@ResourceCollectionToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.ResourceCollectionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordResourceCollection", 
					"@ResourceCollectionToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - ResourcesToolboxTab",
					"@ResourceInstanceToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.ResourceInstanceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordResourceInstance", 
					"@ResourceInstanceToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - ResourcesToolboxTab",
					"@ResourceAttributeToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.ResourceAttributeToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordResourceAttribute", 
					"@ResourceAttributeToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - ResourcesToolboxTab",
					"@ResourceActionToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.ResourceActionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordResourceAction", 
					"@ResourceActionToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxGroup("@ApiStudio - HTTP APIsToolboxTab;api-studio.designer.dll", "ApiStudioIO.ApiStudio - HTTP APIsToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiResourceToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiResourceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordResourceToHttpApi", 
					"@HttpApiResourceToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiGetToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiGetToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordApiGetTool", 
					"@HttpApiGetToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiPutToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiPutToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordHttpApiPutTool", 
					"@HttpApiPutToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiPostToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiPostToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordHttpApiPostTool", 
					"@HttpApiPostToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiDeleteToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiDeleteToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordHttpApiDeleteTool", 
					"@HttpApiDeleteToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiPatchToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiPatchToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordApiGetTool", 
					"@HttpApiPatchToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiHeadToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiHeadToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordApiGetTool", 
					"@HttpApiHeadToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiOptionsToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiOptionsToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordApiGetTool", 
					"@HttpApiOptionsToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiTraceToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiTraceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordApiGetTool", 
					"@HttpApiTraceToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 13)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiRequestToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiRequestToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordHttpApiRequest", 
					"@HttpApiRequestToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 14)]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - HTTP APIsToolboxTab",
					"@HttpApiResponseToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.HttpApiResponseToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordHttpApiResponseStatusCode", 
					"@HttpApiResponseToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 15)]
	[VSShell::ProvideStaticToolboxGroup("@ApiStudio - Data ModelToolboxTab;api-studio.designer.dll", "ApiStudioIO.ApiStudio - Data ModelToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("ApiStudioIO.ApiStudio - Data ModelToolboxTab",
					"@DataModelToolToolboxItem;api-studio.designer.dll", 
					"ApiStudioIO.DataModelToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"F1KeywordDataModelTool", 
					"@DataModelToolToolboxBitmap;api-studio.designer.dll", 
					0xff00ff,
					Index = 16)]
	[VSShell::ProvideEditorFactory(typeof(ApiStudioIOEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(ApiStudioIOEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(ApiStudioIOEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"ApiStudioIO", typeof(ApiStudioIOEditorFactory))]

	internal abstract partial class ApiStudioIOPackageBase : DslShell::AsyncModelingPackage
	{
		protected global::ApiStudioIO.ApiStudioIOToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override System.Threading.Tasks.Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new ApiStudioIOEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::ApiStudioIO.ApiStudioIOToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			ApiStudioIOCommandSet commandSet = new ApiStudioIOCommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			ApiStudioIOClipboardCommandSet clipboardCommandSet = new ApiStudioIOClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(ApiStudioIOExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(ApiStudioIOExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace ApiStudioIO
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::ApiStudioIO.ApiStudioIODirectiveProcessor), global::ApiStudioIO.ApiStudioIODirectiveProcessor.ApiStudioIODirectiveProcessorName, "A directive processor that provides access to ApiStudioIO files")]
	[global::System.Runtime.InteropServices.Guid(Constants.ApiStudioIOPackageId)]
	internal sealed partial class ApiStudioIOPackage : ApiStudioIOPackageBase
	{
	}
}