namespace ApiStudioIO.Common.Models.Http
{
    using System;
    using System.ComponentModel;

    public class HttpResourceParameter : IHttpResource
    {
        public enum HttpApiParameterTypes
        {
            Body, Query, Path
        };
        
        [Category("Hiddend")]
        [Browsable(false)]
        public string Name => $"{Identifier} ({DataType}) [{ Enum.GetName(typeof(HttpApiParameterTypes), FromType)}]";

        [Category("Definition")]
        public string Identifier { get; set; } = "ParameterName";

        [Category("Definition")]
        public string DataType { get; set; } = "string";

        [Category("Definition")]
        public string Description { get; set; } = "This is a description about the API parameter";

        [Category("Definition")]
        public bool IsRequired { get; set; } = false;

        [Category("Definition")]
        public HttpApiParameterTypes FromType { get; set; } = HttpApiParameterTypes.Query;

        [Category("ApiStudio Metadata")]
        public bool IsAutoGenerated { get; set; } = false;
    }
}