namespace ApiStudioIO.Common.Models.Http
{
    using ApiStudioIO.Utility.Extensions;
    using System;
    using System.ComponentModel;

    public class HttpResourceResponseStatusCode : IHttpResource
    {
        public static implicit operator HttpResourceResponseStatusCode(Int32 httpStatus)
        {
            var apiStudioComponent = new HttpResourceResponseStatusCode
            {
                HttpStatus = httpStatus,
                IsAutoGenerated = true
            };
            return apiStudioComponent;
        }


        [Category("Hiddend")]
        [Browsable(false)]
        public string Name => $@"({HttpStatus}) {Description}";

        [Category("Definition")]
        public Int32 HttpStatus { get; set; } = 200;

        [Category("RFC 7231")]
        public string Type => $"{HttpResponseExtension.GetHttpResponseCodeCategory(HttpStatus)}";

        [Category("RFC 7231")]
        public string Description => $"{HttpResponseExtension.GetHttpResponseCodeDescription(HttpStatus)}";

        [Category("ApiStudio Metadata")]
        public bool IsAutoGenerated { get; set; } = false;
    }
}