namespace ApiStudioIO.Common.Models.Http
{
    using System.ComponentModel;

    public abstract class HttpResourceHeaderBase : IHttpResource
    {
        [Category("Definition")]
        public string Name { get; set; }

        [Category("Definition")]
        public string Description { get; set; }

        [Category("Configuration")]
        public bool IsRequired { get; set; }

        [Category("Configuration")]
        public bool AllowEmptyValue { get; set; }

        [Category("ApiStudio Metadata")]
        public bool IsAutoGenerated { get; set; }
    }
}
