namespace ApiStudioIO
{
    using Microsoft.VisualStudio.Modeling;

    internal static class ApiStudioComponentToDomainModelExtension
    {
        internal static HttpApiHeaderRequest ToDomainModel(this ApiStudioComponentHeaderRequest propertyHttpApi, Store store)
        {
            return new HttpApiHeaderRequest(store)
            {
                Name = propertyHttpApi.Name,
                Description = propertyHttpApi.Description,
                IsRequired = propertyHttpApi.IsRequired,
                AllowEmptyValue = propertyHttpApi.AllowEmptyValue,
                IsAutoGenerated = propertyHttpApi.IsAutoGenerated
            };
        }

        internal static HttpApiHeaderResponse ToDomainModel(this ApiStudioComponentHeaderResponse propertyHttpApi, Store store)
        {
            return new HttpApiHeaderResponse(store)
            {
                Name = propertyHttpApi.Name,
                Description = propertyHttpApi.Description,
                IsRequired = propertyHttpApi.IsRequired,
                AllowEmptyValue = propertyHttpApi.AllowEmptyValue,
                IncludeOn = propertyHttpApi.IncludeOn,
                IsAutoGenerated = propertyHttpApi.IsAutoGenerated
            };
        }

        internal static HttpApiMediaTypeRequest ToDomainModel(this ApiStudioComponentMediaTypeRequest propertyHttpApi, Store store)
        {
            return new HttpApiMediaTypeRequest(store)
            {
                DiscreteType = propertyHttpApi.DiscreteTypeName,
                SubType = propertyHttpApi.SubType
            };
        }

        internal static HttpApiMediaTypeResponse ToDomainModel(this ApiStudioComponentMediaTypeResponse propertyHttpApi, Store store)
        {
            return new HttpApiMediaTypeResponse(store)
            {
                DiscreteType = propertyHttpApi.DiscreteTypeName,
                SubType = propertyHttpApi.SubType
            };
        }

        internal static HttpApiParameter ToDomainModel(this ApiStudioComponentParameter propertyHttpApi, Store store)
        {
            return new HttpApiParameter(store)
            {
                Identifier = propertyHttpApi.Identifier,
                DataType = propertyHttpApi.DataType,
                Description = propertyHttpApi.Description,
                FromType = propertyHttpApi.FromType,
                IsRequired = propertyHttpApi.IsRequired,
                IsAutoGenerated = propertyHttpApi.IsAutoGenerated
            };
        }

        internal static HttpApiResponseStatusCode ToDomainModel(this ApiStudioComponentResponseStatusCode propertyHttpApi, Store store)
        {
            return new HttpApiResponseStatusCode(store)
            {
                HttpStatus = propertyHttpApi.HttpStatus
            };
        }
    }
}