namespace ApiStudioIO
{
    using ApiStudioIO.Common.Models.Http;
    using Microsoft.VisualStudio.Modeling;
    using System.ComponentModel;

    internal static class DomainModelHelpers
    {
        internal static HttpApiHeaderRequest ToDomainModel(this HttpResourceHeaderRequest propertyHttpApi, Store store)
        {
            return new HttpApiHeaderRequest(store)
            {
                Name = propertyHttpApi.Name,
                Description = propertyHttpApi.Description,
                IsRequired = propertyHttpApi.IsRequired,
                AllowEmptyValue = propertyHttpApi.AllowEmptyValue,
                IsAutoGenerated = propertyHttpApi.IsAutoGenerated
            };
        }

        internal static HttpApiHeaderResponse ToDomainModel(this HttpResourceHeaderResponse propertyHttpApi, Store store)
        {
            return new HttpApiHeaderResponse(store)
            {
                Name = propertyHttpApi.Name,
                Description = propertyHttpApi.Description,
                IsRequired = propertyHttpApi.IsRequired,
                AllowEmptyValue = propertyHttpApi.AllowEmptyValue,
                IncludeOn = propertyHttpApi.IncludeOn.ToDomainModel(),
                IsAutoGenerated = propertyHttpApi.IsAutoGenerated
            };
        }

        internal static HttpApiMediaTypeRequest ToDomainModel(this HttpResourceMediaTypeRequest propertyHttpApi, Store store)
        {
            return new HttpApiMediaTypeRequest(store)
            {
                DiscreteType = propertyHttpApi.DiscreteTypeName,
                SubType = propertyHttpApi.SubType
            };
        }

        internal static HttpApiMediaTypeResponse ToDomainModel(this HttpResourceMediaTypeResponse propertyHttpApi, Store store)
        {
            return new HttpApiMediaTypeResponse(store)
            {
                DiscreteType = propertyHttpApi.DiscreteTypeName,
                SubType = propertyHttpApi.SubType
            };
        }

        internal static HttpApiParameter ToDomainModel(this HttpResourceParameter propertyHttpApi, Store store)
        {
            return new HttpApiParameter(store)
            {
                Identifier = propertyHttpApi.Identifier,
                DataType = propertyHttpApi.DataType,
                Description = propertyHttpApi.Description,
                FromType = propertyHttpApi.FromType.ToDomainModel(),
                IsRequired = propertyHttpApi.IsRequired,
                IsAutoGenerated = propertyHttpApi.IsAutoGenerated
            };
        }

        internal static HttpApiResponseStatusCode ToDomainModel(this HttpResourceResponseStatusCode propertyHttpApi, Store store)
        {
            return new HttpApiResponseStatusCode(store)
            {
                HttpStatus = propertyHttpApi.HttpStatus
            };
        }



        internal static HttpApiParameterTypes ToDomainModel(this HttpTypeParameterLocation httpTypeParameterLocation)
        {
            switch (httpTypeParameterLocation)
            {
                case HttpTypeParameterLocation.Body: return HttpApiParameterTypes.Body;
                case HttpTypeParameterLocation.Query: return HttpApiParameterTypes.Query;
                case HttpTypeParameterLocation.Path: return HttpApiParameterTypes.Path;

                default:
                    throw new InvalidEnumArgumentException(nameof(httpTypeParameterLocation), (int)httpTypeParameterLocation, typeof(HttpTypeParameterLocation));
            }
        }

        internal static HttpApiHeaderResponseOnTypes ToDomainModel(this HttpTypeHeaderOnResponse httpTypeHeaderOnResponse)
        {
            switch (httpTypeHeaderOnResponse)
            {
                case HttpTypeHeaderOnResponse.OnAlways: return HttpApiHeaderResponseOnTypes.OnAlways;
                case HttpTypeHeaderOnResponse.OnInformation: return HttpApiHeaderResponseOnTypes.OnInformation;
                case HttpTypeHeaderOnResponse.OnSuccess: return HttpApiHeaderResponseOnTypes.OnSuccess;
                case HttpTypeHeaderOnResponse.OnRedirection: return HttpApiHeaderResponseOnTypes.OnRedirection;
                case HttpTypeHeaderOnResponse.OnClientError: return HttpApiHeaderResponseOnTypes.OnClientError;
                case HttpTypeHeaderOnResponse.OnServerError: return HttpApiHeaderResponseOnTypes.OnServerError;

                default:
                    throw new InvalidEnumArgumentException(nameof(httpTypeHeaderOnResponse), (int)httpTypeHeaderOnResponse, typeof(HttpTypeHeaderOnResponse));
            }
        }
    }
}