// The MIT License (MIT)
//
// Copyright (c) 2022 Andrew Butson
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.ComponentModel;

namespace ApiStudioIO.Common.Models.Http
{
    public class HttpResourceParameter : IHttpResource
    {
        [Category("Hiddend")]
        [Browsable(false)]
        public string Name =>
            $"{Identifier} ({DataType}) [{Enum.GetName(typeof(HttpTypeParameterLocation), FromType)}]";

        [Category("Definition")] public string Identifier { get; set; } = "ParameterName";

        [Category("Definition")] public string DataType { get; set; } = "string";

        [Category("Definition")]
        public string Description { get; set; } = "This is a description about the API parameter";

        [Category("Definition")] public bool IsRequired { get; set; } = false;

        [Category("Definition")]
        public HttpTypeParameterLocation FromType { get; set; } = HttpTypeParameterLocation.Query;

        [Category("ApiStudio Metadata")]
        [Browsable(false)]
        public bool IsAutoGenerated { get; set; } = false;
    }
}