// Copyright (c) Andrew Butson.
// Licensed under the MIT License.

using System.ComponentModel;
using Newtonsoft.Json;

namespace ApiStudioIO.Common.Models.Http
{
    public abstract class HttpResourceHeaderBase : IHttpResource
    {
        [Category("Definition")]
        [JsonProperty("name")]
        public string Name { get; set; }

        [Category("Definition")]
        [JsonProperty("description")]
        public string Description { get; set; }

        [Category("Configuration")]
        [JsonProperty("is_required")]
        public bool IsRequired { get; set; }

        [Category("Configuration")]
        [JsonProperty("allow_empty")]
        public bool AllowEmptyValue { get; set; }

        [Category("ApiStudio Metadata")]
        [JsonIgnore]
        [Browsable(false)]
        public bool IsAutoGenerated { get; set; }
    }
}