//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "ApiStudioIO.ApiStudioDiagram")]

namespace ApiStudioIO
{
	/// <summary>
	/// DomainClass ApiStudioDiagram
	/// Description for ApiStudioIO.ApiStudioDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("ApiStudioIO.ApiStudioDiagram.DisplayName", typeof(global::ApiStudioIO.ApiStudioIODomainModel), "ApiStudioIO.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("ApiStudioIO.ApiStudioDiagram.Description", typeof(global::ApiStudioIO.ApiStudioIODomainModel), "ApiStudioIO.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::ApiStudioIO.ApiStudioIODomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("5bdfe02c-2d97-48a7-afd9-8a9acd6ab2c0")]
	public partial class ApiStudioDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::ApiStudioIO.ApiStudioIOToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::ApiStudioIO.HttpApiDelete)
			{
				global::ApiStudioIO.HttpApiDeleteShape newShape = new global::ApiStudioIO.HttpApiDeleteShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiGet)
			{
				global::ApiStudioIO.HttpApiGetShape newShape = new global::ApiStudioIO.HttpApiGetShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiPut)
			{
				global::ApiStudioIO.HttpApiPutShape newShape = new global::ApiStudioIO.HttpApiPutShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiPost)
			{
				global::ApiStudioIO.HttpApiPostShape newShape = new global::ApiStudioIO.HttpApiPostShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiPatch)
			{
				global::ApiStudioIO.HttpApiPatchShape newShape = new global::ApiStudioIO.HttpApiPatchShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiHead)
			{
				global::ApiStudioIO.HttpApiHeadShape newShape = new global::ApiStudioIO.HttpApiHeadShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiOptions)
			{
				global::ApiStudioIO.HttpApiOptionsShape newShape = new global::ApiStudioIO.HttpApiOptionsShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiTrace)
			{
				global::ApiStudioIO.HttpApiTraceShape newShape = new global::ApiStudioIO.HttpApiTraceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.ResourceAttribute)
			{
				global::ApiStudioIO.ResourceAttributeShape newShape = new global::ApiStudioIO.ResourceAttributeShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApi)
			{
				global::ApiStudioIO.HttpApiShape newShape = new global::ApiStudioIO.HttpApiShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.ResourceCollection)
			{
				global::ApiStudioIO.ResourceCollectionShape newShape = new global::ApiStudioIO.ResourceCollectionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.ResourceInstance)
			{
				global::ApiStudioIO.ResourceInstanceShape newShape = new global::ApiStudioIO.ResourceInstanceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.ResourceAction)
			{
				global::ApiStudioIO.ResourceActionShape newShape = new global::ApiStudioIO.ResourceActionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiSuccessResponseModel)
			{
				global::ApiStudioIO.RestToDataModelConnector newShape = new global::ApiStudioIO.RestToDataModelConnector(this.Partition);
				return newShape;
			}
			if(element is global::ApiStudioIO.HttpApiSuccessRequestModel)
			{
				global::ApiStudioIO.DataModelToHttpApiConnector newShape = new global::ApiStudioIO.DataModelToHttpApiConnector(this.Partition);
				return newShape;
			}
			if(element is global::ApiStudioIO.ResourceReferencesResources)
			{
				global::ApiStudioIO.ResourceToResourceConnector newShape = new global::ApiStudioIO.ResourceToResourceConnector(this.Partition);
				return newShape;
			}
			if(element is global::ApiStudioIO.Resource)
			{
				global::ApiStudioIO.ResourceShape newShape = new global::ApiStudioIO.ResourceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.DataModel)
			{
				global::ApiStudioIO.DataModelShape newShape = new global::ApiStudioIO.DataModelShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::ApiStudioIO.ResourceReferencesApis)
			{
				global::ApiStudioIO.ResourceToApiConnector newShape = new global::ApiStudioIO.ResourceToApiConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::ApiStudioIO.ResourceShape.DecoratorsInitialized += ResourceShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.ResourceInstanceShape.DecoratorsInitialized += ResourceInstanceShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.ResourceCollectionShape.DecoratorsInitialized += ResourceCollectionShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.ResourceActionShape.DecoratorsInitialized += ResourceActionShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.ResourceAttributeShape.DecoratorsInitialized += ResourceAttributeShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.DataModelShape.DecoratorsInitialized += DataModelShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiShape.DecoratorsInitialized += HttpApiShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiPutShape.DecoratorsInitialized += HttpApiPutShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiPostShape.DecoratorsInitialized += HttpApiPostShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiDeleteShape.DecoratorsInitialized += HttpApiDeleteShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiGetShape.DecoratorsInitialized += HttpApiGetShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiPatchShape.DecoratorsInitialized += HttpApiPatchShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiHeadShape.DecoratorsInitialized += HttpApiHeadShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiOptionsShape.DecoratorsInitialized += HttpApiOptionsShapeDecoratorMap.OnDecoratorsInitialized;
			global::ApiStudioIO.HttpApiTraceShape.DecoratorsInitialized += HttpApiTraceShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResourceShape.
		/// </summary>
		internal static partial class ResourceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResourceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::ApiStudioIO.Resource.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResourceInstanceShape.
		/// </summary>
		internal static partial class ResourceInstanceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResourceInstanceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				ResourceShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResourceCollectionShape.
		/// </summary>
		internal static partial class ResourceCollectionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResourceCollectionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				ResourceShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResourceActionShape.
		/// </summary>
		internal static partial class ResourceActionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResourceActionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				ResourceShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ResourceAttributeShape.
		/// </summary>
		internal static partial class ResourceAttributeShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ResourceAttributeShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				ResourceShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DataModelShape.
		/// </summary>
		internal static partial class DataModelShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DataModelShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::ApiStudioIO.DataModel.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiShape.
		/// </summary>
		internal static partial class HttpApiShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::ApiStudioIO.Api.DisplayNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiPutShape.
		/// </summary>
		internal static partial class HttpApiPutShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiPutShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiPostShape.
		/// </summary>
		internal static partial class HttpApiPostShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiPostShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiDeleteShape.
		/// </summary>
		internal static partial class HttpApiDeleteShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiDeleteShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiGetShape.
		/// </summary>
		internal static partial class HttpApiGetShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiGetShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiPatchShape.
		/// </summary>
		internal static partial class HttpApiPatchShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiPatchShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiHeadShape.
		/// </summary>
		internal static partial class HttpApiHeadShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiHeadShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiOptionsShape.
		/// </summary>
		internal static partial class HttpApiOptionsShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiOptionsShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HttpApiTraceShape.
		/// </summary>
		internal static partial class HttpApiTraceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HttpApiTraceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				HttpApiShapeDecoratorMap.OnDecoratorsInitialized(sender, e);
				
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::ApiStudioIO.ResourceAssociationConnectAction resourceAssociationConnectAction;
		private global::ApiStudioIO.HttpApiResourceToolConnectAction httpApiResourceToolConnectAction;
		private global::ApiStudioIO.HttpApiRequestToolConnectAction httpApiRequestToolConnectAction;
		private global::ApiStudioIO.HttpApiResponseToolConnectAction httpApiResponseToolConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::ApiStudioIO.ApiStudioIOToolboxHelper.ResourceAssociationFilterString))
				{
					if (this.resourceAssociationConnectAction == null)
					{
						this.resourceAssociationConnectAction = new global::ApiStudioIO.ResourceAssociationConnectAction(this);
						this.resourceAssociationConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.resourceAssociationConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::ApiStudioIO.ApiStudioIOToolboxHelper.HttpApiResourceToolFilterString))
				{
					if (this.httpApiResourceToolConnectAction == null)
					{
						this.httpApiResourceToolConnectAction = new global::ApiStudioIO.HttpApiResourceToolConnectAction(this);
						this.httpApiResourceToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.httpApiResourceToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::ApiStudioIO.ApiStudioIOToolboxHelper.HttpApiRequestToolFilterString))
				{
					if (this.httpApiRequestToolConnectAction == null)
					{
						this.httpApiRequestToolConnectAction = new global::ApiStudioIO.HttpApiRequestToolConnectAction(this);
						this.httpApiRequestToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.httpApiRequestToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::ApiStudioIO.ApiStudioIOToolboxHelper.HttpApiResponseToolFilterString))
				{
					if (this.httpApiResponseToolConnectAction == null)
					{
						this.httpApiResponseToolConnectAction = new global::ApiStudioIO.HttpApiResponseToolConnectAction(this);
						this.httpApiResponseToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.httpApiResponseToolConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.resourceAssociationConnectAction != null)
					{
						this.resourceAssociationConnectAction.Dispose();
						this.resourceAssociationConnectAction = null;
					}
					if(this.httpApiResourceToolConnectAction != null)
					{
						this.httpApiResourceToolConnectAction.Dispose();
						this.httpApiResourceToolConnectAction = null;
					}
					if(this.httpApiRequestToolConnectAction != null)
					{
						this.httpApiRequestToolConnectAction.Dispose();
						this.httpApiRequestToolConnectAction = null;
					}
					if(this.httpApiResponseToolConnectAction != null)
					{
						this.httpApiResponseToolConnectAction.Dispose();
						this.httpApiResponseToolConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// ApiStudioDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x5bdfe02c, 0x2d97, 0x48a7, 0xaf, 0xd9, 0x8a, 0x9a, 0xcd, 0x6a, 0xb2, 0xc0);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ApiStudioDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ApiStudioDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace ApiStudioIO
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiDelete), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiGet), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiPut), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiPost), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiPatch), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHead), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiOptions), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiTrace), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceCollection), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceAction), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApi), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceAttribute), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiSuccessRequestModel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesResources), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.Resource), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.DataModel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiSuccessResponseModel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesApis), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::ApiStudioIO.HttpApiPatch)
				{
					parentElement = GetParentForHttpApiPatch((global::ApiStudioIO.HttpApiPatch)childElement);
				} else
				if(childElement is global::ApiStudioIO.HttpApiHead)
				{
					parentElement = GetParentForHttpApiHead((global::ApiStudioIO.HttpApiHead)childElement);
				} else
				if(childElement is global::ApiStudioIO.HttpApiOptions)
				{
					parentElement = GetParentForHttpApiOptions((global::ApiStudioIO.HttpApiOptions)childElement);
				} else
				if(childElement is global::ApiStudioIO.HttpApiTrace)
				{
					parentElement = GetParentForHttpApiTrace((global::ApiStudioIO.HttpApiTrace)childElement);
				} else
				if(childElement is global::ApiStudioIO.HttpApi)
				{
					parentElement = GetParentForHttpApi((global::ApiStudioIO.HttpApi)childElement);
				} else
				if(childElement is global::ApiStudioIO.Resource)
				{
					parentElement = GetParentForResource((global::ApiStudioIO.Resource)childElement);
				} else
				if(childElement is global::ApiStudioIO.DataModel)
				{
					parentElement = GetParentForDataModel((global::ApiStudioIO.DataModel)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::ApiStudioIO.ApiStudio GetParentForResource( global::ApiStudioIO.Resource root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			public static global::ApiStudioIO.ApiStudio GetParentForDataModel( global::ApiStudioIO.DataModel root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			public static global::ApiStudioIO.ApiStudio GetParentForHttpApi( global::ApiStudioIO.Api root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			public static global::ApiStudioIO.ApiStudio GetParentForHttpApiPatch( global::ApiStudioIO.Api root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			public static global::ApiStudioIO.ApiStudio GetParentForHttpApiHead( global::ApiStudioIO.Api root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			public static global::ApiStudioIO.ApiStudio GetParentForHttpApiOptions( global::ApiStudioIO.Api root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			public static global::ApiStudioIO.ApiStudio GetParentForHttpApiTrace( global::ApiStudioIO.Api root )
			{
				// Segments 0 and 1
				global::ApiStudioIO.ApiStudio result = root.ApiStudio;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesApis), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasResponseStatusCodes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::ApiStudioIO.ResourceReferencesApis)
				{
					global::System.Collections.IEnumerable elements = GetResourceForResourceShapeHttpApiFromLastLink((global::ApiStudioIO.ResourceReferencesApis)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.ResourceShape), "HttpApi", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasParameters)
				{
					global::System.Collections.IEnumerable elements = GetHttpApiForHttpApiShapeRequestParametersFromLastLink((global::ApiStudioIO.HttpApiHasParameters)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestParameters", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasResponseStatusCodes)
				{
					global::System.Collections.IEnumerable elements = GetHttpApiForHttpApiShapeResponseStatusCodesFromLastLink((global::ApiStudioIO.HttpApiHasResponseStatusCodes)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseStatusCodes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasMediaTypeResponse)
				{
					global::System.Collections.IEnumerable elements = GetHttpApiForHttpApiShapeResponseMediaTypesFromLastLink((global::ApiStudioIO.HttpApiHasMediaTypeResponse)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseMediaTypes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasMediaTypeRequest)
				{
					global::System.Collections.IEnumerable elements = GetHttpApiForHttpApiShapeRequestMediaTypesFromLastLink((global::ApiStudioIO.HttpApiHasMediaTypeRequest)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestMediaTypes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasHeaderResponse)
				{
					global::System.Collections.IEnumerable elements = GetHttpApiForHttpApiShapeResponseHeadersFromLastLink((global::ApiStudioIO.HttpApiHasHeaderResponse)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseHeaders", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasHeaderRequest)
				{
					global::System.Collections.IEnumerable elements = GetHttpApiForHttpApiShapeRequestHeadersFromLastLink((global::ApiStudioIO.HttpApiHasHeaderRequest)e.ModelElement);
					UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestHeaders", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetResourceForResourceShapeHttpApiFromLastLink(global::ApiStudioIO.ResourceReferencesApis root)
			{
				// Segment 0
				global::ApiStudioIO.Resource result = root.Resource;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetResourceForResourceShapeHttpApi(global::ApiStudioIO.Api root)
			{
				// Segments 1 and 0
				DslModeling::ReadOnlyLinkedElementCollection<global::ApiStudioIO.Resource> result = root.Resourced;
				return result;
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeRequestParametersFromLastLink(global::ApiStudioIO.HttpApiHasParameters root)
			{
				// Segment 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeRequestParameters(global::ApiStudioIO.HttpApiParameter root)
			{
				// Segments 1 and 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeResponseStatusCodesFromLastLink(global::ApiStudioIO.HttpApiHasResponseStatusCodes root)
			{
				// Segment 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeResponseStatusCodes(global::ApiStudioIO.HttpApiResponseStatusCode root)
			{
				// Segments 1 and 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeResponseMediaTypesFromLastLink(global::ApiStudioIO.HttpApiHasMediaTypeResponse root)
			{
				// Segment 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeResponseMediaTypes(global::ApiStudioIO.HttpApiMediaTypeResponse root)
			{
				// Segments 1 and 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeRequestMediaTypesFromLastLink(global::ApiStudioIO.HttpApiHasMediaTypeRequest root)
			{
				// Segment 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeRequestMediaTypes(global::ApiStudioIO.HttpApiMediaTypeRequest root)
			{
				// Segments 1 and 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeResponseHeadersFromLastLink(global::ApiStudioIO.HttpApiHasHeaderResponse root)
			{
				// Segment 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeResponseHeaders(global::ApiStudioIO.HttpApiHeaderResponse root)
			{
				// Segments 1 and 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeRequestHeadersFromLastLink(global::ApiStudioIO.HttpApiHasHeaderRequest root)
			{
				// Segment 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetHttpApiForHttpApiShapeRequestHeaders(global::ApiStudioIO.HttpApiHeaderRequest root)
			{
				// Segments 1 and 0
				global::ApiStudioIO.HttpApi result = root.HttpApi;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesApis), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasResponseStatusCodes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::ApiStudioIO.ResourceReferencesApis)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetResourceForResourceShapeHttpApiFromLastLink((global::ApiStudioIO.ResourceReferencesApis)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.ResourceShape), "HttpApi", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasParameters)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestParametersFromLastLink((global::ApiStudioIO.HttpApiHasParameters)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestParameters", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasResponseStatusCodes)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseStatusCodesFromLastLink((global::ApiStudioIO.HttpApiHasResponseStatusCodes)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseStatusCodes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasMediaTypeResponse)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseMediaTypesFromLastLink((global::ApiStudioIO.HttpApiHasMediaTypeResponse)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseMediaTypes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasMediaTypeRequest)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestMediaTypesFromLastLink((global::ApiStudioIO.HttpApiHasMediaTypeRequest)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestMediaTypes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasHeaderResponse)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseHeadersFromLastLink((global::ApiStudioIO.HttpApiHasHeaderResponse)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseHeaders", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHasHeaderRequest)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestHeadersFromLastLink((global::ApiStudioIO.HttpApiHasHeaderRequest)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestHeaders", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.Api), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiParameter), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiResponseStatusCode), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiMediaTypeResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiMediaTypeRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHeaderResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHeaderRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::ApiStudioIO.Api && e.DomainProperty.Id == global::ApiStudioIO.Api.DisplayNameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetResourceForResourceShapeHttpApi((global::ApiStudioIO.Api)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.ResourceShape), "HttpApi", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiParameter && e.DomainProperty.Id == global::ApiStudioIO.HttpApiParameter.DisplayNameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestParameters((global::ApiStudioIO.HttpApiParameter)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestParameters", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiResponseStatusCode && e.DomainProperty.Id == global::ApiStudioIO.HttpApiResponseStatusCode.DisplayNameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseStatusCodes((global::ApiStudioIO.HttpApiResponseStatusCode)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseStatusCodes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiMediaTypeResponse && e.DomainProperty.Id == global::ApiStudioIO.HttpApiMediaTypeResponse.DisplayNameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseMediaTypes((global::ApiStudioIO.HttpApiMediaTypeResponse)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseMediaTypes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiMediaTypeRequest && e.DomainProperty.Id == global::ApiStudioIO.HttpApiMediaTypeRequest.DisplayNameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestMediaTypes((global::ApiStudioIO.HttpApiMediaTypeRequest)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestMediaTypes", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHeaderResponse && e.DomainProperty.Id == global::ApiStudioIO.HttpApiHeaderResponse.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseHeaders((global::ApiStudioIO.HttpApiHeaderResponse)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseHeaders", repaintOnly);
				}
				if(e.ModelElement is global::ApiStudioIO.HttpApiHeaderRequest && e.DomainProperty.Id == global::ApiStudioIO.HttpApiHeaderRequest.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestHeaders((global::ApiStudioIO.HttpApiHeaderRequest)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestHeaders", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesApis), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasResponseStatusCodes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::ApiStudioIO.ResourceReferencesApis).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetResourceForResourceShapeHttpApiFromLastLink((global::ApiStudioIO.Api)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.ResourceShape compartmentShape = pel as global::ApiStudioIO.ResourceShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetResourceForResourceShapeHttpApiFromLastLink((global::ApiStudioIO.ResourceReferencesApis)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.ResourceShape), "HttpApi", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetResourceForResourceShapeHttpApi((global::ApiStudioIO.Api)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.ResourceShape), "HttpApi", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestParametersFromLastLink((global::ApiStudioIO.HttpApiParameter)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.HttpApiShape compartmentShape = pel as global::ApiStudioIO.HttpApiShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestParametersFromLastLink((global::ApiStudioIO.HttpApiHasParameters)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestParameters", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestParameters((global::ApiStudioIO.HttpApiParameter)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestParameters", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasResponseStatusCodes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseStatusCodesFromLastLink((global::ApiStudioIO.HttpApiResponseStatusCode)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.HttpApiShape compartmentShape = pel as global::ApiStudioIO.HttpApiShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[1].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseStatusCodesFromLastLink((global::ApiStudioIO.HttpApiHasResponseStatusCodes)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseStatusCodes", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseStatusCodes((global::ApiStudioIO.HttpApiResponseStatusCode)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseStatusCodes", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasMediaTypeResponse).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseMediaTypesFromLastLink((global::ApiStudioIO.HttpApiMediaTypeResponse)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.HttpApiShape compartmentShape = pel as global::ApiStudioIO.HttpApiShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[2].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseMediaTypesFromLastLink((global::ApiStudioIO.HttpApiHasMediaTypeResponse)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseMediaTypes", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseMediaTypes((global::ApiStudioIO.HttpApiMediaTypeResponse)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseMediaTypes", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasMediaTypeRequest).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestMediaTypesFromLastLink((global::ApiStudioIO.HttpApiMediaTypeRequest)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.HttpApiShape compartmentShape = pel as global::ApiStudioIO.HttpApiShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[3].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestMediaTypesFromLastLink((global::ApiStudioIO.HttpApiHasMediaTypeRequest)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestMediaTypes", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestMediaTypes((global::ApiStudioIO.HttpApiMediaTypeRequest)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestMediaTypes", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasHeaderResponse).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseHeadersFromLastLink((global::ApiStudioIO.HttpApiHeaderResponse)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.HttpApiShape compartmentShape = pel as global::ApiStudioIO.HttpApiShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[4].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseHeadersFromLastLink((global::ApiStudioIO.HttpApiHasHeaderResponse)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseHeaders", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseHeaders((global::ApiStudioIO.HttpApiHeaderResponse)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseHeaders", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasHeaderRequest).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestHeadersFromLastLink((global::ApiStudioIO.HttpApiHeaderRequest)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::ApiStudioIO.HttpApiShape compartmentShape = pel as global::ApiStudioIO.HttpApiShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[5].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestHeadersFromLastLink((global::ApiStudioIO.HttpApiHasHeaderRequest)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestHeaders", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestHeaders((global::ApiStudioIO.HttpApiHeaderRequest)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestHeaders", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesApis), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasResponseStatusCodes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasMediaTypeRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderResponse), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiHasHeaderRequest), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::ApiStudioIO.ResourceReferencesApis).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetResourceForResourceShapeHttpApi((global::ApiStudioIO.Api)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.ResourceShape), "HttpApi", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestParameters((global::ApiStudioIO.HttpApiParameter)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestParameters", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasResponseStatusCodes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseStatusCodes((global::ApiStudioIO.HttpApiResponseStatusCode)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseStatusCodes", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasMediaTypeResponse).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseMediaTypes((global::ApiStudioIO.HttpApiMediaTypeResponse)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseMediaTypes", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasMediaTypeRequest).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestMediaTypes((global::ApiStudioIO.HttpApiMediaTypeRequest)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestMediaTypes", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasHeaderResponse).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeResponseHeaders((global::ApiStudioIO.HttpApiHeaderResponse)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "ResponseHeaders", repaintOnly);
					}
				}
				if(typeof(global::ApiStudioIO.HttpApiHasHeaderRequest).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetHttpApiForHttpApiShapeRequestHeaders((global::ApiStudioIO.HttpApiHeaderRequest)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::ApiStudioIO.HttpApiShape), "RequestHeaders", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesResources), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiSuccessRequestModel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.HttpApiSuccessResponseModel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::ApiStudioIO.ResourceReferencesApis), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::ApiStudioIO.ApiStudioDiagram diagram = linkShape.Diagram as global::ApiStudioIO.ApiStudioDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
