//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace ApiStudioIO
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class ApiStudioIOExplorer : ApiStudioIOExplorerBase
	{
		/// <summary>
		/// Constructs a new ApiStudioIOExplorer.
		/// </summary>
		public ApiStudioIOExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the ApiStudioIOExplorerToolWindow.
	/// </summary>
	internal abstract class ApiStudioIOExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new ApiStudioIOExplorerBase.
		/// </summary>
		protected ApiStudioIOExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::ApiStudioIO.ApiStudioIODomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.ResourceCollection.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ResourceCollectionExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.ResourceInstance.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ResourceInstanceExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.ResourceAttribute.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ResourceAttributeExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.ResourceAction.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ResourceActionExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiGet.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiGetExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiDelete.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiDeleteExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiPost.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiPostExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiPut.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiPutExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.DataModel.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DataModelExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiHasHeaderResponse.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiHasHeaderResponseExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiHasHeaderRequest.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiHasHeaderRequestExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiHasMediaTypeRequest.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiHasMediaTypeRequestExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiHasMediaTypeResponse.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiHasMediaTypeResponseExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiHasParameters.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiHasParametersExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::ApiStudioIO.HttpApiHasResponseStatusCodes.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HttpApiHasResponseStatusCodesExplorerImage")), 
							true); 
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.ApiStudioIOExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::ApiStudioIO.ApiStudio.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
	}
}
	


